//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmTech.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TmTech.Resource.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chắc chắn thêm mới dòng này?.
        /// </summary>
        public static string AddNewRow {
            get {
                return ResourceManager.GetString("AddNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xác nhận mục này ?.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vạch đã tồn tại.
        /// </summary>
        public static string barcodehasexists {
            get {
                return ResourceManager.GetString("barcodehasexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu không được nhỏ hơn ngày hiện tại.
        /// </summary>
        public static string begindatemustbiggerthantoday {
            get {
                return ResourceManager.GetString("begindatemustbiggerthantoday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn hủy mục này?.
        /// </summary>
        public static string cancelapprove {
            get {
                return ResourceManager.GetString("cancelapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn 1 serie trước..
        /// </summary>
        public static string chooseaserieforproduct {
            get {
                return ResourceManager.GetString("chooseaserieforproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa lưu thay đổi, bạn có muốn thoát không?.
        /// </summary>
        public static string closewithoutsave {
            get {
                return ResourceManager.GetString("closewithoutsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm đã tồn tại.
        /// </summary>
        public static string codehasexist {
            get {
                return ResourceManager.GetString("codehasexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty đã tồn tại.
        /// </summary>
        public static string CompanyisExists {
            get {
                return ResourceManager.GetString("CompanyisExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới công ty.
        /// </summary>
        public static string CompanyTitleCreateNew {
            get {
                return ResourceManager.GetString("CompanyTitleCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật công ty.
        /// </summary>
        public static string CompanyTitleUpdate {
            get {
                return ResourceManager.GetString("CompanyTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo mới.
        /// </summary>
        public static string createfailed {
            get {
                return ResourceManager.GetString("createfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới thành công.
        /// </summary>
        public static string createsuccess {
            get {
                return ResourceManager.GetString("createsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có thay đổi chưa được lưu, bạn có muốn thoát?.
        /// </summary>
        public static string datahasbeenchanged {
            get {
                return ResourceManager.GetString("datahasbeenchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thất bại.
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giao hàng không được nhỏ hơn ngày hiện tại.
        /// </summary>
        public static string deliverydatemustbiggerthanpobegin {
            get {
                return ResourceManager.GetString("deliverydatemustbiggerthanpobegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn công ty.
        /// </summary>
        public static string deputyhasnocompany {
            get {
                return ResourceManager.GetString("deputyhasnocompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc không được nhỏ hơn ngày hiện tại.
        /// </summary>
        public static string enftimemustbiigerthantoday {
            get {
                return ResourceManager.GetString("enftimemustbiigerthantoday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thành công.
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập đủ thông tin.
        /// </summary>
        public static string hasnoinfomation {
            get {
                return ResourceManager.GetString("hasnoinfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn công ty..
        /// </summary>
        public static string hasnotcompanyselected {
            get {
                return ResourceManager.GetString("hasnotcompanyselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập giá.
        /// </summary>
        public static string hasnotprice {
            get {
                return ResourceManager.GetString("hasnotprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập số lượng.
        /// </summary>
        public static string hasnotquantity {
            get {
                return ResourceManager.GetString("hasnotquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hoạt động.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể xóa/chỉnh sửa do mục này đã được xác nhận..
        /// </summary>
        public static string itemwasapproved {
            get {
                return ResourceManager.GetString("itemwasapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu tạo nguyên vật liệu.
        /// </summary>
        public static string MateralCreateTilteForm {
            get {
                return ResourceManager.GetString("MateralCreateTilteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu sửa nguyên vât liệu.
        /// </summary>
        public static string MateralEditTilteForm {
            get {
                return ResourceManager.GetString("MateralEditTilteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống.
        /// </summary>
        public static string MsgCodeNotNull {
            get {
                return ResourceManager.GetString("MsgCodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        public static string MsgInValidPhone {
            get {
                return ResourceManager.GetString("MsgInValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm không hợp lệ.
        /// </summary>
        public static string MsgInValidProduct {
            get {
                return ResourceManager.GetString("MsgInValidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu dữ liệu input..
        /// </summary>
        public static string MsgMissingData {
            get {
                return ResourceManager.GetString("MsgMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống.
        /// </summary>
        public static string MsgNameNotNull {
            get {
                return ResourceManager.GetString("MsgNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa?.
        /// </summary>
        public static string MSGRemoveItem {
            get {
                return ResourceManager.GetString("MSGRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn sản phẩm.
        /// </summary>
        public static string noproductselected {
            get {
                return ResourceManager.GetString("noproductselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        public static string passwordinvalid {
            get {
                return ResourceManager.GetString("passwordinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẫu không được có khoảng trắng.
        /// </summary>
        public static string passwordnotallowspace {
            get {
                return ResourceManager.GetString("passwordnotallowspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp.
        /// </summary>
        public static string passwordnotsame {
            get {
                return ResourceManager.GetString("passwordnotsame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu quá ngắn.
        /// </summary>
        public static string passwordtooshort {
            get {
                return ResourceManager.GetString("passwordtooshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning đang trong quá trình thực hiện hoặc đã kết thúc, bạn không thể chỉnh sửa..
        /// </summary>
        public static string planningcouldnotbeedit {
            get {
                return ResourceManager.GetString("planningcouldnotbeedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string producthasnomaterial {
            get {
                return ResourceManager.GetString("producthasnomaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm.
        /// </summary>
        public static string productnotfound {
            get {
                return ResourceManager.GetString("productnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa.
        /// </summary>
        public static string removefailed {
            get {
                return ResourceManager.GetString("removefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa mục này ?.
        /// </summary>
        public static string removeitem {
            get {
                return ResourceManager.GetString("removeitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string removesuccess {
            get {
                return ResourceManager.GetString("removesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu thông tin phiếu nhập nguyên vật liệu.
        /// </summary>
        public static string Update_ImportID {
            get {
                return ResourceManager.GetString("Update_ImportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật.
        /// </summary>
        public static string updatefailed {
            get {
                return ResourceManager.GetString("updatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string updatesuccess {
            get {
                return ResourceManager.GetString("updatesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã tồn tại.
        /// </summary>
        public static string userhasexist {
            get {
                return ResourceManager.GetString("userhasexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản không được có khoảng trắng.
        /// </summary>
        public static string usernotallowspace {
            get {
                return ResourceManager.GetString("usernotallowspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Việt Nam đồng.
        /// </summary>
        public static string VND {
            get {
                return ResourceManager.GetString("VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
