//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmTech_v1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MesgBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MesgBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TmTech_v1.MesgBox", typeof(MesgBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mục này?.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vạch đã tồn tại.
        /// </summary>
        internal static string barcodehasexists {
            get {
                return ResourceManager.GetString("barcodehasexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa lưu thay đổi, bạn có muốn thoát không?.
        /// </summary>
        internal static string closewithoutsave {
            get {
                return ResourceManager.GetString("closewithoutsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm đã tồn tại.
        /// </summary>
        internal static string codehasexist {
            get {
                return ResourceManager.GetString("codehasexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo mới.
        /// </summary>
        internal static string createfailed {
            get {
                return ResourceManager.GetString("createfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới thành công.
        /// </summary>
        internal static string createsuccess {
            get {
                return ResourceManager.GetString("createsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có thay đổi chưa được lưu, bạn có muốn thoát?.
        /// </summary>
        internal static string datahasbeenchanged {
            get {
                return ResourceManager.GetString("datahasbeenchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thành công.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập đủ thông tin.
        /// </summary>
        internal static string hasnoinfomation {
            get {
                return ResourceManager.GetString("hasnoinfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập giá.
        /// </summary>
        internal static string hasnotprice {
            get {
                return ResourceManager.GetString("hasnotprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập số lượng.
        /// </summary>
        internal static string hasnotquantity {
            get {
                return ResourceManager.GetString("hasnotquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống.
        /// </summary>
        internal static string MsgCodeNotNull {
            get {
                return ResourceManager.GetString("MsgCodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string MsgInValidPhone {
            get {
                return ResourceManager.GetString("MsgInValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm không hợp lệ.
        /// </summary>
        internal static string MsgInValidProduct {
            get {
                return ResourceManager.GetString("MsgInValidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu dữ liệu input..
        /// </summary>
        internal static string MsgMissingData {
            get {
                return ResourceManager.GetString("MsgMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống.
        /// </summary>
        internal static string MsgNameNotNull {
            get {
                return ResourceManager.GetString("MsgNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa?.
        /// </summary>
        internal static string MSGRemoveItem {
            get {
                return ResourceManager.GetString("MSGRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn sản phẩm.
        /// </summary>
        internal static string noproductselected {
            get {
                return ResourceManager.GetString("noproductselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        internal static string passwordinvalid {
            get {
                return ResourceManager.GetString("passwordinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp.
        /// </summary>
        internal static string passwordnotsame {
            get {
                return ResourceManager.GetString("passwordnotsame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu quá ngắn.
        /// </summary>
        internal static string passwordtooshort {
            get {
                return ResourceManager.GetString("passwordtooshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning đang trong quá trình thực hiện hoặc đã kết thúc, bạn không thể chỉnh sửa..
        /// </summary>
        internal static string planningcouldnotbeedit {
            get {
                return ResourceManager.GetString("planningcouldnotbeedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        internal static string producthasnomaterial {
            get {
                return ResourceManager.GetString("producthasnomaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm.
        /// </summary>
        internal static string productnotfound {
            get {
                return ResourceManager.GetString("productnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa.
        /// </summary>
        internal static string removefailed {
            get {
                return ResourceManager.GetString("removefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa mục này ?.
        /// </summary>
        internal static string removeitem {
            get {
                return ResourceManager.GetString("removeitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string removesuccess {
            get {
                return ResourceManager.GetString("removesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật.
        /// </summary>
        internal static string updatefailed {
            get {
                return ResourceManager.GetString("updatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        internal static string updatesuccess {
            get {
                return ResourceManager.GetString("updatesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã tồn tại.
        /// </summary>
        internal static string userhasexist {
            get {
                return ResourceManager.GetString("userhasexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
